### ISSUE TITLE
$ccEagerType no longer working

### ISSUE THREAD

**Issue by eternalwaves** [bendrucker/angular-credit-cards#101]

**Comment by bendrucker** [comment]
More information would be helpful

**Comment by eternalwaves** [comment]
Go to your demo, change uses of $ccType to $ccEagerType, add the cc-eager-type directive to the ccNumber input. Credit card type is no longer detected.

http://plnkr.co/edit/Hn7RGVsa0kc978Gdm1gb

**Comment by kjots** [comment]
We encountered this issue recently and were able to work around it by adding the following directive to the credit card number input:

```js
angular.module('...').directive('ccEagerTypeFix', function () {
    return {
        restrict: 'A',
        link: function (scope, element, attrs) {
            element.on('input', function () {
                scope.$digest();
            });
        }
    };
});
```

Note that we use `ng-model-options="{ updateOn: 'blur' }"` on the credit card number input to delay validation until the user has navigated away from the input.  Removing this option causes the `$ccEagerType` value to be available as expected, however this is not an option for us due to business requirements.

**Comment by bendrucker** [comment]
The demo was on a super old version. I updated it to the latest and added cc-eager-type to the demo. There was no problem with the library.

@kjots Your issue is entirely separate. I don't see how the eager type attribute could cause that. Give this a shot against the latest version. Possible #107 will fix this for you.
