### ISSUE TITLE
After upgrading from 2.3.4 to 3.1.4 the form now allows entering 19 digits (it looks like: xxxx xxxx xxxx xxxx xxx), before it was allowing the usual 16 digits I want.

### ISSUE THREAD

**Issue by ohjames** [bendrucker/angular-credit-cards#123]

**Comment by ohjames** [comment]
If I enter any more than 16 digits then it quite rightly raises a validation error so I guess the fact it allows me to enter them is a bug rather than a new type of credit card I'm not familiar with.

**Comment by ohjames** [comment]
The options I'm using:

```html
  <input type="text"
         ng-model="payment.cardNumber"
         cc-number
         cc-format
         cc-eager-type
         cc-type="cardType"
         name="cardNumber"
         class="form-control"
         placeholder="{{placeholder.cardNumber}}"
         required
         mongoose-error />
```

**Comment by bendrucker** [comment]
The Visa spec allows for 19 digits which is why you're seeing that behavior.

**Comment by bendrucker** [comment]
Btw, I understand that stuff like this is hard to keep track of. I made this lib ultra modular so that the regexes and other validation stuff could evolve independent of any framework.

Here's Visa:

https://github.com/bendrucker/creditcards-types/blob/acaf9813056e452f80b70c1ad1eb2ab7529fcef6/src/types.js#L7-L11

And you can try the Luhn algorithm here:

https://tonicdev.com/571826753121781100a4a9cb/577fcf13741fad1300f32ec7

**Comment by ohjames** [comment]
@bendrucker thanks for putting up with my ignorance on these matters :+1:
