### ISSUE TITLE
cc-exp-month and cc-exp-year set incorrect validity keys

### ISSUE THREAD

**Issue by joshnoe** [bendrucker/angular-credit-cards#156]
To reproduce:
1. Add this html to the demo plunkr to view the error keys of the Month field:
`<div>{{ccForm.ccExpMonth.$error}}</div>`

2. Enter a non-numeric value in either the Month field such as "aa"

Expected: `$error` key should be "ccExpMonth"
Actual: `$error` key is **"parse"**

3. Delete the value from the Month field

Expected: `$error` key should be "required"
Actual: `$error` key is **"parse"**

**Comment by brianroadifer** [comment]
That should be the expected behavior though. You are trying to enter a string as a number that doesn't parse to a number.
The reason why it is not showing the error for required is because it only shows when the input is told to be required and is blank.

**Comment by joshnoe** [comment]
> That should be the expected behavior though. You are trying to enter a string as a number that doesn't parse to a number.
I don't know about "expected". As a user of this library, I'd expect ccExpMonth to be an all-encompassing abstraction for invalid input. It seems to be portrayed this way in the README, and there's no mention of the parse message. Maybe I'm just not familiar with ng-message conventions, but mentioning this parse message in the README could be helpful?

>The reason why it is not showing the error for required is because it only shows when the input is told to be required and is blank.
Right, forgot to mention in the steps to add the `required` attribute to the input. If you do this, enter a value, and then delete it, it still sends a "parse" message.

**Comment by brianroadifer** [comment]
I see what you are getting at now because it also happens as well when you enter a number as well.
I am a user of this library as well, I guess until it gets fixed, make your `ng-show` look like this 

`<span ng-show="form.input.$error.required || form.input.$error.parse">Required</span>`

Hope that helps.

**Comment by bendrucker** [comment]
Hiya,

Based on the following I think the library is doing the right thing here. If you can find supporting documentation suggesting otherwise I'm happy to reopen/reconsider:

> Angular now automatically adds a 'parse' key to all $error collections with its value set accordingly - true if any of the parsers returned undefined, false otherwise.

http://stackoverflow.com/a/25739987/906162

**Comment by joshnoe** [comment]
@bendrucker I see. At the very least, please consider adding this to the README? I've never come across this convention being used in another library, so it may not be expected for some users :)

The 2nd issue I posted regarding `parse` being sent instead of `required` still stands I believe? As it is now, a `required` message will never be sent for these inputs. I guess technically you could argue that an empty string isn't a parseable input in this case, but it's a stretch.

**Comment by bendrucker** [comment]
You're welcome to send a PR if you think there's a good place to describe this concisely. Since it's standard Angular behavior I typically try to avoid documenting the quirks of the framework by default.

An empty string isn't parseable, what else could I return but `undefined`?

I encourage you to send PRs with at least a failing test if you expect things to work a certain way. Otherwise it's hard to know that your preference doesn't break other expectations.
