### ISSUE TITLE
Wanna parse exp month as string. how?!

### ISSUE THREAD

**Issue by HashemKhalifa** [bendrucker/angular-credit-cards#173]
I tried to use type number with max length and still passing expire month as a number, 

for example
wanna pass it as "06" but it gives me 6.

**Comment by bendrucker** [comment]
Hi, there is no option to not parse the field to a number. I do not plan to add one since number is the correct storage type for a month.

You could add another directive that captures the view value before cc-number gets to parse it or any other number of options depending on your specific circumstances.
