### ISSUE TITLE
CVC maxlength based on card-type?

### ISSUE THREAD

**Issue by thatmarvin** [bendrucker/angular-credit-cards#33]
Does it make sense to change `maxlength` based on `cc-type`?

Not sure if 3 or 4 is a better default when there's no card type — 3 because it's more common, 4 because it's more permissive (like for whatever reason a user fills in the cvc before card type is detected).

**Comment by bendrucker** [comment]
So I actually thought about this when I made that decision, but it's definitely good you brought it up so I can explain. This decision was made before I implemented eager typing, but the logic still holds. 

The default absolutely has to be 4. You can't rely on `$ccType` because that's going to be undefined not only initially, but also when the card is invalid. `$ccEagerType` could be defined, but that's optional (changeable though). 

The maxlength has meaning to the browser and the potential for confusion here is huge. A user won't intend to type more than four digits into the CVC field. But what if they mistype their card as 35... (JCB) instead of 34 (Amex). Forcibly preventing the user from typing that 4th digit of their CVC will frustrate them. A 4 digit CVC there would be invalid, but we only know that if we let the user type the whole value.

**Comment by thatmarvin** [comment]
Ok, sounds reasonable. Thanks!
