### ISSUE TITLE
Modifying the card number model does not play well with cc-format 

### ISSUE THREAD

**Issue by makeitrein** [bendrucker/angular-credit-cards#36]
http://plnkr.co/edit/cU68yLPPqAVRDeHZQMQ7?p=preview

This is probably very edge-casey, but any input/advice would be appreciated. In my Angular project, my users use a numpad to fill in data into the checkout form. I would love to be able to use the new cc-format option, but at least on Chrome on my Macbook Air, the numbers reset after the first 5 digits are added.

**Comment by bendrucker** [comment]
The problem here stems from the fact that your model is invalid until a full number is entered. What's weird is that the first 4 digits are being recorded to the model (4444) but then the next 4 results in the model being `''` (empty string). The latter is the expected behavior that should be happening the whole time. 

You're going to need to use `ngModelOptions` and its `allowInvalid` method to implement this. The weird behavior is a bug, but the fix will be ensuring that the model is always undefined, even w/ cc-format.

**Comment by ajbraus** [comment]
+1 - Mine ends before I can enter the last number: 4242 4242 4242 4242 424

**Comment by jensengar** [comment]
I also get an extra 3 characters on the cc number.

**Comment by bendrucker** [comment]
You've got 19 digits typed out -- that's the maximum. Don't think that's a bug.

**Comment by bendrucker** [comment]
Just implemented a fix. If you want users to be able to type on the keyboard and use your UI keypad you'll need to use the [`allowInvalid` model option](https://code.angularjs.org/1.5.5/docs/api/ng/directive/ngModelOptions).
